# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];


  #kernel
  boot.kernelParams = [ "pci=noaer" ];
  #boot.blacklistedKernelModules = [ "tpm" "tpm_tis_core" "tpm_tis" "tpm_crb" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42cdbf35-3300-450f-bb0f-d941906cd77e";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/796a75e3-4533-4d06-9303-0a20ddd8e66b"; }
    ];

  # Enable sound.
  sound.enable = true;
  hardware = {
  	pulseaudio.enable = true;
	  pulseaudio.package = pkgs.pulseaudioFull; #for bluetooth headset support
	  bluetooth.enable = true;
    #Intel
	  cpu.intel.updateMicrocode = true;
    #graphics
  	opengl.driSupport32Bit = true;
	  opengl.enable = true;
	  opengl.extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau ];
  };

  #services.mbpfan.minFanSpeed = 500;

  #for nvidia prime with my double graphics laptops
  services.xserver.videoDrivers = [ "nouveau" ];

  nix.maxJobs = lib.mkDefault 4;
  #powerManagement.enable = false;
  #powerManagement.cpuFreqGovernor = "ondemand";
  #powerManagement.cpufreq.min = 2000000;
  #services.acpid.enable = true;
  services.tlp.enable = true;
}
