# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];


  #kernel
  boot.kernelParams = [ "pci=noaer" ];
  #boot.blacklistedKernelModules = [ "tpm" "tpm_tis_core" "tpm_tis" "tpm_crb" ];
  #boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42cdbf35-3300-450f-bb0f-d941906cd77e";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/796a75e3-4533-4d06-9303-0a20ddd8e66b"; }
    ];

  # Enable sound.
  sound.enable = true;
  hardware = {
    pulseaudio.enable = true;
    pulseaudio.package = pkgs.pulseaudioFull; #for bluetooth headset support
    bluetooth.enable = true;
    #Intel
    cpu.intel.updateMicrocode = true;
    #graphics
    opengl = {
  	  driSupport32Bit = true;
      enable = true;
      extraPackages = with pkgs; [
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
        intel-media-driver # LIBVA_DRIVER_NAME=iHD to use this
      ];
    };
    bumblebee = {
      enable = true;
      driver = "nvidia";
    };
  };

  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };


  #Graphics drivers and screen tear fix
  services.xserver = {
    enable=true;
    videoDrivers = [ "intel" ];
    deviceSection = ''
      Option "DRI" "2"
      Option "TearFree" "true"
      '';
  };

  nix.maxJobs = lib.mkDefault 4;
  services.tlp.enable = true;
  services.tlp.extraConfig = ''
    TLP_DEFAULT_MODE=BAT
    TLP_PERSISTENT_DEFAULT=0
    CPU_SCALING_GOVERNOR_ON_AC=powersave
    CPU_SCALING_GOVERNOR_ON_BAT=powersave
    CPU_SCALING_MIN_FREQ_ON_BAT=400000
    CPU_SCALING_MIN_FREQ_ON_AC=400000
    CPU_SCALING_MAX_FREQ_ON_BAT=2700000
    CPU_SCALING_MAX_FREQ_ON_AC=3500000
    ENERGY_PERF_POLICY_ON_AC=power
    ENERGY_PERF_POLICY_ON_BAT=power
    CPU_HWP_ON_AC=power
    CPU_HWP_ON_BAT=power
    CPU_BOOST_ON_AC=1
    CPU_BOOST_ON_BAT=0
    SCHED_POWERSAVE_ON_AC=1
    SCHED_POWERSAVE_ON_BAT=1
  '';

}
